debug = false
headless = false
save_path = "output/"

[primitive_detection]
method = "region_growing"
use_regularization = true
max_distance_to_plane = 0.01
max_accepted_angle = 50
min_region_size = 50
neigbor_K = 12
save_result = false
alpha_scale = 1.2 #use by ray shooting

[regularization]
merge_coplane = false #todo:need to adjust alpha shape
parallelism = true
orthogonality = true
coplanarity = true
Z_symmetry = false
paral_degree = 1 #tolerance for parallelism / orthogonality
coplane_dist = 0.01 #tolerance for coplanarity


[partition]
method = "BSP"
expand_scale = 0.3 #make it more robust to missing primitive

[surface_extraction]
method = "alphaShape_rays"
lambda = 0.1
missing_ground = false #assume there is the ground at -Z_plane
use_area_weight = true
alpha_scale = 1.2 #use by area_weight
